ejs ./ejs/pages/index.ejs -o ./public/index.html
ejs ./ejs/pages/accueil.ejs -o ./public/accueil.html
ejs ./ejs/pages/boutique.ejs -o ./public/boutique.html
ejs ./ejs/pages/contact.ejs -o ./public/contact.html
ejs ./ejs/pages/lol.ejs -o ./public/lol.html
ejs ./ejs/pages/expircuzepram-200mg.ejs -o ./public/expircuzepram-200mg.html
ejs ./ejs/pages/expircuzepram-400mg.ejs -o ./public/expircuzepram-400mg.html
ejs ./ejs/pages/expircuzepram-flash.ejs -o ./public/expircuzepram-flash.html
ejs ./ejs/pages/expircuzepram-kids.ejs -o ./public/expircuzepram-kids.html
ejs ./ejs/pages/panier.ejs -o ./public/panier.html